/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClientCard: typeof import('./src/components/ClientCard.vue')['default']
    ClientList: typeof import('./src/components/ClientList.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
  }
}
